"""
Recomputes the HW3 Part 2 summary tables from the raw per-query results
(reports/hw03/raw/retrieval_results.jsonl + chunk_stats.json) and writes
reports/hw03/METRICS.md.

This is the "along with a script that recomputes the summary tables below
from it" file the assignment asks for -- it never re-runs retrieval, it only
re-derives the summary numbers from the already-saved raw data, so it's fast
and doesn't need the embedding model loaded again.

Run after retrieval_pipeline.py:
    python3 scripts/summarize_metrics.py
"""
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "reports" / "hw03" / "raw"
METRICS_PATH = ROOT / "reports" / "hw03" / "METRICS.md"

CONFIDENT_WRONG_THRESHOLD = 0.35  # cosine above this counts as "confidently scored"


def load_rows():
    rows = []
    with open(RAW_DIR / "retrieval_results.jsonl", encoding="utf-8") as f:
        for line in f:
            rows.append(json.loads(line))
    return rows


def main():
    rows = load_rows()
    chunk_stats = json.loads((RAW_DIR / "chunk_stats.json").read_text())

    by_technique = defaultdict(list)
    for r in rows:
        by_technique[r["technique"]].append(r)

    # --- per-technique summary table -----------------------------------
    technique_order = ["token", "semantic", "sentence_window"]
    labels = {"token": "Token", "semantic": "Semantic", "sentence_window": "Sentence window"}
    summary = {}
    for tech in technique_order:
        tech_rows = by_technique[tech]
        rank1 = [r["cosine_sim"] for r in tech_rows if r["rank"] == 1]
        all_cos = [r["cosine_sim"] for r in tech_rows]
        latencies = sorted({(r["question_id"], r["latency_ms"]) for r in tech_rows})
        latency_vals = [v for _, v in latencies]

        # Recall@k: fraction of questions (that have a real expected source
        # file, i.e. excluding the intentional "no answer exists" probe
        # question) where that file shows up anywhere in that question's
        # top-k retrieved chunks for this technique.
        by_q = defaultdict(list)
        for r in tech_rows:
            by_q[r["question_id"]].append(r)
        hits, scored_qs = 0, 0
        for qid, qrows in by_q.items():
            expected = qrows[0]["expected_source_file"]
            if not expected or expected.startswith("NONE"):
                continue
            scored_qs += 1
            if any(r["source_file"] == expected for r in qrows):
                hits += 1
        recall_at_k = hits / scored_qs if scored_qs else float("nan")

        summary[tech] = {
            "chunks": chunk_stats[tech]["num_chunks"],
            "avg_chunk_len": chunk_stats[tech]["avg_chunk_len"],
            "top1_cosine": sum(rank1) / len(rank1) if rank1 else float("nan"),
            "mean_at_k_cosine": sum(all_cos) / len(all_cos) if all_cos else float("nan"),
            "recall_at_k": recall_at_k,
            "mean_latency_ms": sum(latency_vals) / len(latency_vals) if latency_vals else float("nan"),
        }

    # --- confidently-wrong retrieval ------------------------------------
    wrong_candidates = [
        r
        for r in rows
        if r["expected_source_file"]
        and not r["expected_source_file"].startswith("NONE")
        and r["source_file"] != r["expected_source_file"]
        and r["cosine_sim"] >= CONFIDENT_WRONG_THRESHOLD
    ]
    # Also always include the intentional probe question's top hits, since
    # by design no document answers it.
    probe_rows = [r for r in rows if r["expected_source_file"] and r["expected_source_file"].startswith("NONE")]
    wrong_candidates += [r for r in probe_rows if r["rank"] == 1]
    wrong_candidates.sort(key=lambda r: r["cosine_sim"], reverse=True)
    top_wrong = wrong_candidates[0] if wrong_candidates else None

    # --- write METRICS.md -------------------------------------------------
    lines = []
    lines.append("# METRICS.md -- HW3 Part 2 Retrieval Quality Comparison\n")
    lines.append("Auto-generated by `scripts/summarize_metrics.py` from `reports/hw03/raw/retrieval_results.jsonl`.\n")
    lines.append("Recomputing this file never re-runs retrieval -- it only re-derives these numbers from the saved raw data.\n")
    lines.append("| Technique | Chunks | Avg chunk length | Top-1 cosine | Mean@k cosine | Recall@k | Mean retrieval latency (ms) |")
    lines.append("|---|---|---|---|---|---|---|")
    for tech in technique_order:
        s = summary[tech]
        lines.append(
            f"| {labels[tech]} | {s['chunks']} | {s['avg_chunk_len']:.1f} | {s['top1_cosine']:.4f} | "
            f"{s['mean_at_k_cosine']:.4f} | {s['recall_at_k']:.2f} | {s['mean_latency_ms']:.2f} |"
        )

    lines.append("\n## Confidently-scored wrong retrieval\n")
    if top_wrong:
        lines.append(
            f"Question **{top_wrong['question_id']}** (\"{top_wrong['question']}\") with technique "
            f"**{top_wrong['technique']}** retrieved `{top_wrong['source_file']}` at rank {top_wrong['rank']} "
            f"with cosine similarity **{top_wrong['cosine_sim']:.4f}** -- but the expected source was "
            f"`{top_wrong['expected_source_file']}`.\n"
        )
        lines.append(f"> Retrieved chunk preview: \"{top_wrong['preview']}\"\n")
        lines.append(
            "**Why the embedding likely considered it similar:** (fill in after reading the preview above -- "
            "typically shared vocabulary/topic words, e.g. both chunks mention the same pathogen, 'recall', "
            "'states', or 'consumer guidance' language, even though the specific product/company differs.)\n"
        )
    else:
        lines.append(
            "No retrieval crossed the confidence threshold while being wrong. Consider lowering "
            "CONFIDENT_WRONG_THRESHOLD in this script, or adding another adversarial question to questions.yaml.\n"
        )

    METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)
    METRICS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {METRICS_PATH}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
